AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SQS

Globals:
  Function:
    Timeout: 5
    CodeUri: src/
    Runtime: nodejs12.x

Resources:
  DeadLetter:
    Type: AWS::SQS::Queue

  RawQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      # FifoQueue: true
      # QueueName: test.fifo
      # ContentBasedDeduplication: true
      # KmsDataKeyReusePeriodSeconds: 5
      # MaximumMessageSize: 262144
      # MessageRetentionPeriod: 1209600
      # ReceiveMessageWaitTimeSeconds: 10
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetter.Arn
        maxReceiveCount: 4
      Tags:
        - Key: Series
          Value: FlashSam
      VisibilityTimeout: 120

  RawQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Id: Policy12324323
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !GetAtt RawQueue.Arn
            Principal:
              AWS:
                - "[aws_account_id]"
                - "[aws_user_arn]"
      Queues:
        - !Ref RawQueue

  TriggeredFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt RawQueue.Arn
            BatchSize: 10
            Enabled: true

Outputs:
  RawSqsUrl:
    Description: URL of the SQS Queue
    Value: !Ref RawQueue
  
  DeadLetterUrl:
    Description: URL of Deadletter SQS Queue
    Value: !Ref DeadLetter